pipeline:
  name: ci-gaar-477
  identifier: cigaar477
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_477
        repoName: ci_cd
        build: <+input>
  stages:
    - stage:
        name: ci-gar
        identifier: cigar
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcp477
                    host: us-central1-docker.pkg.dev
                    projectID: project-cb80b961-01f1-443f-bfb
                    imageName: demo-repo1/my-app1
                    tags:
                      - "1.1"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s477
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: cd
        identifier: cd
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: newservice477
          environment:
            environmentRef: dev_477
            deployToAll: false
            infrastructureDefinitions:
              - identifier: newinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
